### ISSUE TITLE
yaw pitch roll calculation principle

### ISSUE THREAD

**Issue by yyqgood** [WIKI2020/FacePose_pytorch#11]
Hello there:
Can you provide the calculation principle of yaw pitch roll? especially:
yaw = int(yaw * 71.58 + 0.7037)
pitch = int(1.497 * pitch_dis + 18.97)
The experience value in these two lines of code?

**Comment by WIKI2020** [comment]
These parameters are generated based on our own dataset

**Comment by yyqgood** [comment]
@WIKI2020 
Hello, can you provide the corresponding code? If it is convenient, my email is: godloveyyq@163.com. Thank you!

**Comment by windspirit95** [comment]
In my point, you could try this method to find the suitable hyperparameters for pitch and yaw's calibrating formulas:
- First you collecting raw yaw (pitch) value (you could try to use camera and shaking your head, record image with raw value of yaw (pitch)) and labeled with your own ground truth angle.
- Find the line of best fit: https://www.kite.com/python/answers/how-to-plot-a-line-of-best-fit-in-python
--> yaw = int(yaw * m + b)

**Comment by yyqgood** [comment]
@windspirit95 Glad to receive your reply, I will try it, thanks!

**Comment by kurbobo** [comment]
Hello, can you provide the corresponding code? If it is convenient, my email is: kurbobo239@gmail.com. Thank you!

**Comment by sharkzeeh** [comment]
> These parameters are generated based on our own dataset

Hi, what is the dataset? WIDERFACE?
