### ISSUE TITLE
Masked face affect to pitch value and stability

### ISSUE THREAD

**Issue by windspirit95** [WIKI2020/FacePose_pytorch#13]
Hi,
Thank you for your great work. Your model works great with high precision and speed.
About testing with webcam and masked face, the yaw seems to be fine, while the pitch when I head-up could not be predicted.
So do you have any plan to improve the pretrained based on the current issue? Thank you
My email is windspirit95@gmail.com.

**Comment by WIKI2020** [comment]
Thank you, mask face is not supported at present; the accuracy will be improved next time

**Comment by windspirit95** [comment]
Thank you 👍
