### ISSUE TITLE
About demo  face precision

### ISSUE THREAD

**Issue by wywywy01** [WIKI2020/FacePose_pytorch#3]
hi ,i saw the pose in you demo face as blow , and the yaw is 40, apparently it can not be true ,have you check the  actual results?
![image](https://user-images.githubusercontent.com/22450352/92902715-11209680-f454-11ea-9f6c-8dd4c2712987.png)

**Comment by WIKI2020** [comment]
The sample image might be between 35 ° and 40 ° ，and you can take photos by yourself (confirm your angle) to test and confirm
