### ISSUE TITLE
model

### ISSUE THREAD

**Issue by zengwbz** [WIKI2020/FacePose_pytorch#4]
Hello Hi, can you share the ultra-high precision model you trained? my email:1303281435@qq.com, thanks!

**Comment by WIKI2020** [comment]
We will release it in October or November. Thank you for your attention！

**Comment by zengwbz** [comment]
Can you tell me how accurately you train the PFLD?

**Comment by WIKI2020** [comment]
We annotate a huge amount of face data, very accurate

**Comment by changkaizhi** [comment]
Does this face detection support multiple people?

**Comment by KasparPeterson** [comment]
Thanks for the amazing work!
Is there any update on the release of the ultra-high precision model?

My email is: kasparpeterson@hotmail.com

**Comment by liangying-Ke** [comment]
Thanks for the amazing work!

My email is: b0743035@ems.niu.edu.tw

**Comment by chenbolinstudent** [comment]
Hello , can you share the ultra-high precision model you trained? and training code to me?my email:
2549853330@qq.com
thanks!

**Comment by zengwbz** [comment]
I will close this issue, this is a lie
